.PHONY: clean All

All:
	@echo "----------Building project:[ PlayerMaker - Debug ]----------"
	@cd "PlayerMaker" && "$(MAKE)" -f  "PlayerMaker.mk"
clean:
	@echo "----------Cleaning project:[ PlayerMaker - Debug ]----------"
	@cd "PlayerMaker" && "$(MAKE)" -f  "PlayerMaker.mk" clean
